title: "Soil Microbial Ecology Lab"
author: "Kaile Zhang"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", url: "/"}
  - {title: "People", url: "/people/"}
  - {title: "Research", url: "/research/",
      children:
      - title: "Soil–microbiome–plant-environment interactions"
        url: "/research/Soil–microbiome–plant-environment interactions"
      - title: "Impacts of abiotic stress on terrestrial ecosystems"
        url: "/research/Impacts of abiotic stress on terrestrial ecosystems"
      }
  - {title: "Publications", file: "publication.md"}
  - {title: "Blog"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "zhangk@lincolnu.edu"}
  - {title: Github, icon: github, url: "https://github.com/KaileZhang-lab"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
